#!/usr/bin/env bash
# Convert schema.json (extracted from the spec workbook) into Schema.gs
# so Apps Script can use it without runtime JSON file I/O.
set -euo pipefail
cd "$(dirname "$0")"

if [ ! -f schema.json ]; then
  echo "schema.json missing. Re-run the Python extractor."; exit 1
fi

cat > Schema.gs <<'HEADER'
// AUTO-GENERATED by build-schema.sh — do not edit by hand.
// Source: J_USE_Complete_GoogleSheet_Output_Workbook.xlsx
//        + j_use_finalized_schema_151_mapping.xlsx

const SCHEMA =
HEADER

cat schema.json >> Schema.gs
echo ";" >> Schema.gs

echo "✓ Wrote $(wc -l < Schema.gs) lines to Schema.gs"
