#!/usr/bin/env bash
# Generate Templates.gs from the two Email_*.html files so the Apps Script
# code can use the templates without HtmlService.createHtmlOutputFromFile()
# (which rejects Outlook VML / conditional-comment markup).
set -euo pipefail
cd "$(dirname "$0")"

esc() {
  # Escape backslashes, then backticks, then ${ sequences for template literals.
  sed -e 's/\\/\\\\/g' -e 's/`/\\`/g' -e 's/\${/\\${/g' "$1"
}

{
  echo "// AUTO-GENERATED by build-templates.sh — do not edit by hand."
  echo "// Source: Email_Applicant.html + Email_Grants.html"
  echo
  echo "const EMAIL_APPLICANT_HTML = \`"
  esc Email_Applicant.html
  echo "\`;"
  echo
  echo "const EMAIL_GRANTS_HTML = \`"
  esc Email_Grants.html
  echo "\`;"
} > Templates.gs

echo "✓ Wrote $(wc -l < Templates.gs) lines to Templates.gs"
