// AUTO-GENERATED by build-schema.sh — do not edit by hand.
// Source: J_USE_Complete_GoogleSheet_Output_Workbook.xlsx + schema_151_mapping.xlsx
// Used by writeToSchemaTabs_() to populate the 9 form-fed tabs and create
// (with headers only) the reviewer/analyst tabs in the same workbook.

const SCHEMA_TAB_HEADERS = {
  "applications_master": [
    "application_id",
    "reference_id",
    "submission_timestamp",
    "application_status",
    "review_score",
    "routing_decision",
    "is_test_submission",
    "project_parish_eligibility_status",
    "future_pipeline_flag",
    "lead_flag",
    "pipeline_reason",
    "org_name",
    "registration_type",
    "registration_type_other",
    "organization_category",
    "organization_category_other",
    "date_of_formation",
    "registration_number",
    "org_parish",
    "has_bank_account",
    "contact_name",
    "contact_title",
    "contact_gender",
    "contact_email",
    "contact_phone",
    "contact_address",
    "website",
    "social_media",
    "soe_head_name",
    "soe_head_title",
    "soe_head_email",
    "soe_head_phone",
    "gov_head_name",
    "gov_head_title",
    "gov_head_email",
    "gov_head_phone",
    "project_parish",
    "project_location",
    "project_area_type",
    "climate_challenge_primary",
    "climate_challenge_secondary",
    "exposure_description",
    "vulnerability_description",
    "adaptive_capacity_description",
    "coping_strategy_description",
    "system_description",
    "project_title",
    "system_transformation",
    "housing_vulnerability_level",
    "housing_vulnerability_description",
    "adaptation_logic_biophysical",
    "adaptation_logic_beneficiaries",
    "nbcs_primary_interventions",
    "nbcs_secondary_interventions",
    "nbcs_primary_other_text",
    "nbcs_secondary_other_text",
    "project_summary",
    "project_description",
    "beneficiary_estimation_method",
    "total_direct_beneficiaries",
    "total_indirect_beneficiaries",
    "public_beneficiaries",
    "target_groups_summary",
    "target_groups_other_text",
    "women_percentage",
    "youth_percentage",
    "low_income_percentage",
    "vulnerable_percentage",
    "gender_inclusion_description",
    "gender_analysis_findings",
    "gbv_mitigation_measures",
    "jobs_created",
    "jobs_for_women",
    "people_receiving_skills_training",
    "women_led_enterprises_supported",
    "women_employed",
    "youth_employed",
    "persons_with_disabilities_employed",
    "vulnerability_to_benefits_link",
    "benefit_intensity_level",
    "benefit_realisation_timing",
    "benefit_traceability_summary",
    "benefit_traceability_mechanism_preview",
    "value_pathway",
    "value_pathway_rationale",
    "market_customer",
    "market_customer_other",
    "market_revenue_model",
    "market_operations_management_coverage",
    "hybrid_anchor_partner",
    "hybrid_public_goods",
    "hybrid_market_percentage",
    "public_agency_adoption",
    "public_ndc_alignment",
    "sustainability_description",
    "scaling_potential",
    "scaling_pathway",
    "partner_summary",
    "enabling_conditions_reflection",
    "maintenance_who",
    "maintenance_funding",
    "maintenance_duration",
    "maintenance_fallback",
    "learning_format",
    "total_project_cost",
    "grant_requested",
    "co_financing_amount",
    "budget_breakdown_summary",
    "proposed_start_date",
    "proposed_end_date",
    "iucn_criterion_biodiversity",
    "iucn_criterion_governance",
    "iucn_criterion_grant_compliance",
    "iucn_criterion_mitigation",
    "iucn_criterion_tradeoffs",
    "tna_overall_score",
    "tna_priority_area_1",
    "tna_priority_area_2",
    "tna_priority_area_3",
    "nbcsCompletenessScore",
    "beneficiaryCoverageSummary",
    "dataQualityFlag",
    "document_urls_summary",
    "accessibility_needs",
    "accessibility_details",
    "additional_comments",
    "signature_name",
    "signature_title",
    "signature_date",
    "declaration_1",
    "declaration_2",
    "declaration_3",
    "declaration_4",
    "full_application_pdf_url",
    "summary_pdf_url"
  ],
  "multiselect_selections": [
    "application_id",
    "reference_id",
    "field_name",
    "selected_option",
    "selected_option_label",
    "source_step"
  ],
  "outcome_metrics": [
    "application_id",
    "reference_id",
    "outcome_row_id",
    "outcome_type",
    "metric_name",
    "baseline_value",
    "target_value",
    "unit",
    "how_measured",
    "time_horizon"
  ],
  "implementation_roles": [
    "application_id",
    "reference_id",
    "role_row_id",
    "role_name",
    "organization_name",
    "responsibility"
  ],
  "tna_scores": [
    "application_id",
    "reference_id",
    "competency_area",
    "score",
    "priority_flag",
    "notes"
  ],
  "documents": [
    "application_id",
    "reference_id",
    "document_row_id",
    "document_type",
    "file_name",
    "file_url",
    "mime_type",
    "uploaded_timestamp"
  ],
  "benefit_traceability": [
    "application_id",
    "reference_id",
    "traceability_row_id",
    "outcome_label",
    "sector_system",
    "target_groups",
    "benefit_mechanism"
  ],
  "focus_lens_selections": [
    "application_id",
    "reference_id",
    "lens_row_id",
    "lens_name",
    "selected_option",
    "selected_option_label"
  ],
  "enablers_detail": [
    "application_id",
    "reference_id",
    "enabler_row_id",
    "enabler_name",
    "status",
    "notes"
  ],
  "leads": [
    "lead_id",
    "reference_id",
    "submission_timestamp",
    "lead_status",
    "source_flow",
    "project_parish_eligibility_status",
    "org_name",
    "registration_type",
    "organization_category",
    "contact_name",
    "contact_title",
    "contact_email",
    "contact_phone",
    "contact_gender",
    "org_parish",
    "project_parish",
    "project_location",
    "project_area_type",
    "climate_challenge_primary",
    "climate_challenge_secondary",
    "exposure_description",
    "vulnerability_description",
    "adaptive_capacity_description",
    "coping_strategy_description",
    "notes"
  ],
  "future_pipeline": [
    "application_id",
    "reference_id",
    "submission_timestamp",
    "future_pipeline_flag",
    "pipeline_reason",
    "organization_name",
    "registration_type",
    "contact_name",
    "contact_email",
    "contact_phone",
    "project_parish",
    "project_parish_eligibility_status",
    "project_title",
    "project_summary",
    "climate_challenge_primary",
    "climate_challenge_secondary",
    "nbcs_primary_interventions",
    "target_groups_summary",
    "total_direct_beneficiaries",
    "value_pathway",
    "grant_requested",
    "document_urls_summary",
    "dataQualityFlag",
    "nbcsCompletenessScore",
    "reviewer_notes"
  ],
  "tna_analytics": [
    "application_id",
    "reference_id",
    "organization_name",
    "project_title",
    "tna_overall_score",
    "highest_scoring_area",
    "lowest_scoring_area",
    "priority_area_1",
    "priority_area_2",
    "priority_area_3",
    "number_of_high_priority_gaps",
    "readiness_band",
    "qualitative_gap_summary",
    "capacity_building_recommendation",
    "technical_assistance_notes",
    "reviewer_tna_comment"
  ],
  "iucn_alignment_report": [
    "application_id",
    "reference_id",
    "organization_name",
    "project_title",
    "iucn_criterion_1_score",
    "iucn_criterion_1_summary",
    "iucn_criterion_2_score",
    "iucn_criterion_2_summary",
    "iucn_criterion_3_score",
    "iucn_criterion_3_summary",
    "iucn_criterion_4_score",
    "iucn_criterion_4_summary",
    "iucn_criterion_5_score",
    "iucn_criterion_5_summary",
    "iucn_criterion_6_score",
    "iucn_criterion_6_summary",
    "iucn_criterion_7_score",
    "iucn_criterion_7_summary",
    "iucn_criterion_8_score",
    "iucn_criterion_8_summary",
    "iucn_overall_alignment_score",
    "iucn_alignment_band",
    "iucn_key_strengths",
    "iucn_key_gaps",
    "iucn_reviewer_notes"
  ],
  "capital_alignment_report": [
    "application_id",
    "reference_id",
    "organization_name",
    "project_title",
    "project_parish",
    "value_pathway",
    "af_alignment_score",
    "af_alignment_band",
    "af_rationale",
    "af_readiness_level",
    "af_key_gaps",
    "gcf_alignment_score",
    "gcf_alignment_band",
    "gcf_rationale",
    "gcf_readiness_level",
    "gcf_key_gaps",
    "philanthropy_alignment_score",
    "philanthropy_alignment_band",
    "philanthropy_rationale",
    "philanthropy_best_use_case",
    "blended_alignment_score",
    "blended_structure_type",
    "blended_rationale",
    "impact_alignment_score",
    "impact_instrument_fit",
    "impact_rationale",
    "primary_capital_recommendation",
    "secondary_capital_option",
    "capital_stacking_strategy",
    "recommended_instrument",
    "investment_readiness_band",
    "capital_pathway_notes"
  ],
  "chart_specs": [
    "dashboard_tab",
    "chart_title",
    "chart_type",
    "source_tab",
    "data_logic"
  ],
  "formula_library": [
    "target_tab",
    "kpi_or_use",
    "formula",
    "notes"
  ],
  "validation_rules": [
    "field_or_rule",
    "rule",
    "notes"
  ],
  "lookups": [
    "list_name",
    "value"
  ],
  "field_inventory_reference": [
    "note"
  ]
};

const APPLICATIONS_MASTER_MAP = {
  "bankAccount": "has_bank_account",
  "contactGender": "contact_gender",
  "contactName": "contact_name",
  "contactTitle": "contact_title",
  "dateOfFormation": "date_of_formation",
  "email": "contact_email",
  "govHeadEmail": "gov_head_email",
  "govHeadName": "gov_head_name",
  "govHeadPhone": "gov_head_phone",
  "govHeadTitle": "gov_head_title",
  "orgAddress": "contact_address",
  "orgCategory": "organization_category",
  "orgCategoryOtherText": "organization_category_other",
  "orgName": "org_name",
  "orgParish": "org_parish",
  "phone": "contact_phone",
  "regNumber": "registration_number",
  "regType": "registration_type",
  "regTypeOtherText": "registration_type_other",
  "socialMedia": "social_media",
  "soeHeadEmail": "soe_head_email",
  "soeHeadName": "soe_head_name",
  "soeHeadPhone": "soe_head_phone",
  "soeHeadTitle": "soe_head_title",
  "website": "website",
  "classification": "project_area_type",
  "copingDescription": "coping_strategy_description",
  "location": "project_location",
  "parish": "project_parish",
  "projectTitle": "project_title",
  "systemTransformation": "system_transformation",
  "housingContextDesc": "housing_vulnerability_description",
  "housingVulnerability": "housing_vulnerability_level",
  "logicBeneficiaries": "adaptation_logic_beneficiaries",
  "logicBiophysical": "adaptation_logic_biophysical",
  "nbcsOtherText": "nbcs_primary_other_text",
  "nbcsSecondaryOtherText": "nbcs_secondary_other_text",
  "projectDescription": "project_description",
  "summary": "project_summary",
  "adaptiveCapacity": "adaptive_capacity_description",
  "beneficiaryEstimation": "beneficiary_estimation_method",
  "benefitIntensity": "benefit_intensity_level",
  "benefitTiming": "benefit_realisation_timing",
  "directBeneficiaries": "total_direct_beneficiaries",
  "exposureDescription": "exposure_description",
  "gbvMitigationMeasures": "gbv_mitigation_measures",
  "genderAnalysisFindings": "gender_analysis_findings",
  "inclusionApproach": "gender_inclusion_description",
  "indirectBeneficiaries": "total_indirect_beneficiaries",
  "jobsCreated": "jobs_created",
  "jobsWomen": "jobs_for_women",
  "lowIncomePct": "low_income_percentage",
  "peopleTrained": "people_receiving_skills_training",
  "pwdEmployed": "persons_with_disabilities_employed",
  "targetGroupsOtherText": "target_groups_other_text",
  "vulnerabilityBenefitsLink": "vulnerability_to_benefits_link",
  "vulnerabilityDescription": "vulnerability_description",
  "vulnerablePct": "vulnerable_percentage",
  "womenEmployed": "women_employed",
  "womenEnterprises": "women_led_enterprises_supported",
  "womenPct": "women_percentage",
  "youthEmployed": "youth_employed",
  "youthPct": "youth_percentage",
  "hybridAnchorPartner": "hybrid_anchor_partner",
  "hybridMarketPct": "hybrid_market_percentage",
  "hybridPublicGoods": "hybrid_public_goods",
  "marketCustomer": "market_customer",
  "marketCustomerOther": "market_customer_other",
  "marketOMCoverage": "market_operations_management_coverage",
  "marketRevenue": "market_revenue_model",
  "pathway": "value_pathway",
  "pathwayRationale": "value_pathway_rationale",
  "publicAgencyAdopt": "public_agency_adoption",
  "publicBeneficiaries": "public_beneficiaries",
  "publicNDCAlign": "public_ndc_alignment",
  "sustainability": "sustainability_description",
  "scalingPathway": "scaling_pathway",
  "scalingPotential": "scaling_potential",
  "enablingConditionsReflection": "enabling_conditions_reflection",
  "endDate": "proposed_end_date",
  "juseRequest": "grant_requested",
  "maintenanceDuration": "maintenance_duration",
  "maintenanceFallback": "maintenance_fallback",
  "maintenanceFunding": "maintenance_funding",
  "maintenanceWho": "maintenance_who",
  "otherFunding": "co_financing_amount",
  "startDate": "proposed_start_date",
  "totalCost": "total_project_cost",
  "accessibilityDetails": "accessibility_details",
  "accessibilityNeeds": "accessibility_needs",
  "iucn_biodiversity": "iucn_criterion_biodiversity",
  "iucn_governance": "iucn_criterion_governance",
  "iucn_grant_compliance": "iucn_criterion_grant_compliance",
  "iucn_mitigation": "iucn_criterion_mitigation",
  "iucn_tradeoffs": "iucn_criterion_tradeoffs",
  "learningFormat": "learning_format",
  "additionalComments": "additional_comments",
  "authDate": "signature_date",
  "authName": "signature_name",
  "authTitle": "signature_title",
  "declaration1": "declaration_1",
  "declaration2": "declaration_2",
  "declaration3": "declaration_3",
  "declaration4": "declaration_4"
};

const MULTISELECT_FIELDS = [
  {
    "html_name": "climateChallenge",
    "source_step": "2"
  },
  {
    "html_name": "copingMechanisms",
    "source_step": "2"
  },
  {
    "html_name": "hazards",
    "source_step": "2"
  },
  {
    "html_name": "systemFlows",
    "source_step": "2"
  },
  {
    "html_name": "nbcsIntervention",
    "source_step": "3"
  },
  {
    "html_name": "nbcsSecondary",
    "source_step": "3"
  },
  {
    "html_name": "genderConsiderations",
    "source_step": "4"
  },
  {
    "html_name": "socialBenefits",
    "source_step": "4"
  },
  {
    "html_name": "targetGroups",
    "source_step": "4"
  },
  {
    "html_name": "enablers",
    "source_step": "6"
  },
  {
    "html_name": "priorityNeeds",
    "source_step": "8"
  }
];

// 9 tabs populated by every successful submission
const FORM_POPULATED_TABS = ["applications_master","multiselect_selections","outcome_metrics","implementation_roles","tna_scores","documents","benefit_traceability","focus_lens_selections","enablers_detail"];

// ----- Static metadata rows from the spec workbook -----
// Populated once via populateStaticTabs_() (idempotent: only writes if a tab
// has no data rows yet beyond the header).
const SCHEMA_STATIC_ROWS = {
  "chart_specs": [
    [
      "dashboard",
      "Submissions by Parish",
      "Bar chart",
      "applications_master",
      "project_parish vs count"
    ],
    [
      "dashboard",
      "Applications by Status",
      "Donut chart",
      "applications_master",
      "application_status vs count"
    ],
    [
      "dashboard",
      "Value Pathway Mix",
      "Donut chart",
      "applications_master",
      "value_pathway vs count"
    ],
    [
      "dashboard",
      "Registration Type Mix",
      "Bar chart",
      "applications_master",
      "registration_type vs count"
    ],
    [
      "dashboard",
      "Climate Hazards Selected",
      "Horizontal bar",
      "multiselect_selections",
      "selected_option where field_name=hazards"
    ],
    [
      "dashboard",
      "Target Groups Reached",
      "Horizontal bar",
      "multiselect_selections",
      "selected_option where field_name=targetGroups"
    ],
    [
      "portfolio_capital_dashboard",
      "Capital Alignment Mix",
      "Donut chart",
      "capital_alignment_report",
      "primary_capital_recommendation vs count"
    ],
    [
      "portfolio_capital_dashboard",
      "Pipeline Funnel",
      "Bar chart",
      "leads/future_pipeline/master",
      "Leads → Pipeline → Submitted → Shortlisted → Awarded"
    ]
  ],
  "formula_library": [
    [
      "dashboard",
      "Total Entries (All)",
      0,
      "Counts master rows excluding header"
    ],
    [
      "dashboard",
      "Leads",
      0,
      "Counts leads tab rows excluding header"
    ],
    [
      "dashboard",
      "Future Pipeline",
      0,
      "Counts future pipeline rows"
    ],
    [
      "dashboard",
      "Pathway % of Total",
      0,
      "Replace pathway_count with row cell reference"
    ],
    [
      "portfolio_capital_dashboard",
      "AF aligned count",
      0,
      "Assumes AF score column G"
    ]
  ],
  "validation_rules": [
    [
      "All phone fields",
      "Must match 1-xxx-xxx-xxxx",
      "Apply to contact, SOE, government phone fields"
    ],
    [
      "proposed_end_date",
      "Must be in 2027",
      "Submission blocked if invalid"
    ],
    [
      "benefit_traceability",
      "At least 1 complete row required",
      "Outcome, sector/system, groups, mechanism, intensity, timing"
    ],
    [
      "Other parish → Exit",
      "Write Step 1 + Step 2 to leads",
      "Do not expose sheet to applicant"
    ],
    [
      "Other parish → Proceed Anyway",
      "Flag future pipeline",
      "Also retain full master record"
    ]
  ],
  "lookups": [
    [
      "application_status",
      "in_progress"
    ],
    [
      "application_status",
      "submitted"
    ],
    [
      "application_status",
      "shortlisted"
    ],
    [
      "application_status",
      "awarded"
    ],
    [
      "application_status",
      "rejected"
    ],
    [
      "project_parish_eligibility_status",
      "eligible"
    ],
    [
      "project_parish_eligibility_status",
      "not_currently_eligible"
    ],
    [
      "future_pipeline_flag",
      "yes"
    ],
    [
      "future_pipeline_flag",
      "no"
    ],
    [
      "lead_flag",
      "yes"
    ],
    [
      "lead_flag",
      "no"
    ]
  ],
  "field_inventory_reference": [
    [
      "See the separate finalized schema workbook for the full 151-field inventory and mapping."
    ]
  ]
};
